## **In general, consumer loans and credit cards are the most typical retail products where credit risk modelling is applied. In this project, we will focus on consumer loans.**

---

### In this project, we will use an open-source dataset titled "Lending Club Loan Data," which contains comprehensive information on all loans issued by Lending Club, a U.S. based peer-to-peer lending company from 2007 to 2015. The dataset is available at https://www.kaggle.com/datasets/adarshsng/lending-club-loan-data-csv?resource=download. 

---

### The separate files are provided,

#### 1) loan.csv : Complete dataset.
#### 2) LCDataDictionary.xlsx : Detailing the variables in the Dataset.

---
### Libraries used.

> !pip install pandas
> 
> !pip install numpy
> 
> !pip install openpyxl
> 
> !pip install seaborn
> 
> !pip install scikit-learn

In [1]:
import warnings
import pandas as pd
from IPython.display import display, Markdown

In [2]:
warnings.filterwarnings('ignore') # to supress warnings

> ### **First we will have a look at the dataset, the variables, and the description provided.**

In [3]:
variables = pd.read_excel('dataset/LCDataDictionary.xlsx')
loan_dataset = pd.read_csv('dataset/loan.csv') # Loading data.

> ### **After exploring the variables in the dataset, some stood out as important for our credit risk model. Their definitions are provided below.**

In [4]:
imp_variables = ['grade', 'emp_length', 'emp_title', 'term', 'earliest_cr_line', 'issue_d',
                'sub_grade', 'home_ownership', 'verification_status', 'loan_status', 'purpose',
                 'addr_state', 'initial_list_status','total_rev_hi_lim', 'annual_inc', 
                 'acc_now_delinq', 'total_acc', 'pub_rec', 'open_acc', 'inq_last_6mths',
                 'delinq_2yrs','dti', 'mths_since_last_record', 'mths_since_last_delinq', 
                'funded_amnt', 'loan_amnt', 'funded_amnt_inv']

for i in range(len(variables['LoanStatNew'])):
    if variables['LoanStatNew'][i] in imp_variables:
        display(Markdown(f"**{variables['LoanStatNew'][i]}**: {variables['Description'][i]}  \n"))

**acc_now_delinq**: The number of accounts on which the borrower is now delinquent.

**addr_state**: The state provided by the borrower in the loan application

**annual_inc**: The self-reported annual income provided by the borrower during registration.

**delinq_2yrs**: The number of 30+ days past-due incidences of delinquency in the borrower's credit file for the past 2 years

**dti**: A ratio calculated using the borrower’s total monthly debt payments on the total debt obligations, excluding mortgage and the requested LC loan, divided by the borrower’s self-reported monthly income.

**earliest_cr_line**: The month the borrower's earliest reported credit line was opened

**emp_length**: Employment length in years. Possible values are between 0 and 10 where 0 means less than one year and 10 means ten or more years.

**emp_title**: The job title supplied by the Borrower when applying for the loan.*

**funded_amnt**: The total amount committed to that loan at that point in time.

**funded_amnt_inv**: The total amount committed by investors for that loan at that point in time.

**grade**: LC assigned loan grade

**home_ownership**: The home ownership status provided by the borrower during registration or obtained from the credit report. Our values are: RENT, OWN, MORTGAGE, OTHER

**initial_list_status**: The initial listing status of the loan. Possible values are – W, F

**inq_last_6mths**: The number of inquiries in past 6 months (excluding auto and mortgage inquiries)

**issue_d**: The month which the loan was funded

**loan_amnt**: The listed amount of the loan applied for by the borrower. If at some point in time, the credit department reduces the loan amount, then it will be reflected in this value.

**loan_status**: Current status of the loan

**mths_since_last_delinq**: The number of months since the borrower's last delinquency.

**mths_since_last_record**: The number of months since the last public record.

**open_acc**: The number of open credit lines in the borrower's credit file.

**pub_rec**: Number of derogatory public records

**purpose**: A category provided by the borrower for the loan request.

**sub_grade**: LC assigned loan subgrade

**term**: The number of payments on the loan. Values are in months and can be either 36 or 60.

**total_acc**: The total number of credit lines currently in the borrower's credit file

**verification_status**: Indicates if income was verified by LC, not verified, or if the income source was verified

In [5]:
# To get pandas to show all columns in our dataframe, we use
pd.options.display.max_columns = None # To show all rows, we could use "pd.options.display.max_rows = None"
loan_dataset[:10]

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,2500,2500,2500.0,36 months,13.56,84.92,C,C1,Chef,10+ years,RENT,55000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,109xx,NY,18.24,0.0,Apr-2001,1.0,NaN,45.0,9.0,1.0,4341,10.3,34.0,w,2386.02,2386.02,167.02,167.02,113.98,53.04,0.0,0.0,0.0,Feb-2019,84.92,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,16901.0,2.0,2.0,1.0,2.0,2.0,12560.0,69.0,2.0,7.0,2137.0,28.0,42000.0,1.0,11.0,2.0,9.0,1878.0,34360.0,5.9,0.0,0.0,140.0,212.0,1.0,1.0,0.0,1.0,NaN,2.0,NaN,0.0,2.0,5.0,3.0,3.0,16.0,7.0,18.0,5.0,9.0,0.0,0.0,0.0,3.0,100.0,0.0,1.0,0.0,60124.0,16901.0,36500.0,18124.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,30000,30000,30000.0,60 months,18.94,777.23,D,D2,Postmaster,10+ years,MORTGAGE,90000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,713xx,LA,26.52,0.0,Jun-1987,0.0,71.0,75.0,13.0,1.0,12315,24.2,44.0,w,29387.75,29387.75,1507.11,1507.11,612.25,894.86,0.0,0.0,0.0,Feb-2019,777.23,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,1208.0,321915.0,4.0,4.0,2.0,3.0,3.0,87153.0,88.0,4.0,5.0,998.0,57.0,50800.0,2.0,15.0,2.0,10.0,24763.0,13761.0,8.3,0.0,0.0,163.0,378.0,4.0,3.0,3.0,4.0,NaN,4.0,NaN,0.0,2.0,4.0,4.0,9.0,27.0,8.0,14.0,4.0,13.0,0.0,0.0,0.0,6.0,95.0,0.0,1.0,0.0,372872.0,99468.0,15000.0,94072.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,5000,5000,5000.0,36 months,17.97,180.69,D,D1,Administrative,6 years,MORTGAGE,59280.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,490xx,MI,10.51,0.0,Apr-2011,0.0,NaN,NaN,8.0,0.0,4599,19.1,13.0,w,4787.21,4787.21,353.89,353.89,212.79,141.10,0.0,0.0,0.0,Feb-2019,180.69,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,110299.0,0.0,1.0,0.0,2.0,14.0,7150.0,72.0,0.0,2.0,0.0,35.0,24100.0,1.0,5.0,0.0,4.0,18383.0,13800.0,0.0,0.0,0.0,87.0,92.0,15.0,14.0,2.0,77.0,NaN,14.0,NaN,0.0,0.0,3.0,3.0,3.0,4.0,6.0,7.0,3.0,8.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,136927.0,11749.0,13800.0,10000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,4000,4000,4000.0,36 months,18.94,146.51,D,D2,IT Supervisor,10+ years,MORTGAGE,92000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,985xx,WA,16.74,0.0,Feb-2006,0.0,NaN,NaN,10.0,0.0,5468,78.1,13.0,w,3831.93,3831.93,286.71,286.71,168.07,118.64,0.0,0.0,0.0,Feb-2019,146.51,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,686.0,305049.0,1.0,5.0,3.0,5.0,5.0,30683.0,68.0,0.0,0.0,3761.0,70.0,7000.0,2.0,4.0,3.0,5.0,30505.0,1239.0,75.2,0.0,0.0,62.0,154.0,64.0,5.0,3.0,64.0,NaN,5.0,NaN,0.0,1.0,2.0,1.0,2.0,7.0,2.0,3.0,2.0,10.0,0.0,0.0,0.0,3.0,100.0,100.0,0.0,0.0,385183.0,36151.0,5000.0,44984.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,30000,30000,30000.0,60 months,16.14,731.78,C,C4,Mechanic,10+ years,MORTGAGE,57250.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,212xx,MD,26.35,0.0,Dec-2000,0.0,NaN,NaN,12.0,0.0,829,3.6,26.0,w,29339.02,29339.02,1423.21,1423.21,660.98,762.23,0.0,0.0,0.0,Feb-2019,731.78,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,116007.0,3.0,5.0,3.0,5.0,4.0,28845.0,89.0,2.0,4.0,516.0,54.0,23100.0,1.0,0.0,0.0,9.0,9667.0,8471.0,8.9,0.0,0.0,53.0,216.0,2.0,2.0,2.0,2.0,NaN,13.0,NaN,0.0,2.0,2.0,3.0,8.0,9.0,6.0,15.0,2.0,12.0,0.0,0.0,0.0,5.0,92.3,0.0,0.0,0.0,157548.0,29674.0,9300.0,32332.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,5550,5550,5550.0,36 months,15.02,192.45,C,C3,Director COE,10+ years,MORTGAGE,152500.0,Not Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,461xx,IN,37.94,0.0,Sep-2002,3.0,NaN,NaN,18.0,0.0,53854,48.1,44.0,w,5302.50,5302.50,377.95,377.95,247.50,130.45,0.0,0.0,0.0,Feb-2019,192.45,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,685749.0,1.0,7.0,2.0,3.0,4.0,131524.0,72.0,1.0,4.0,17584.0,58.0,111900.0,2.0,4.0,6.0,8.0,40338.0,23746.0,64.0,0.0,0.0,195.0,176.0,10.0,4.0,6.0,20.0,NaN,3.0,NaN,0.0,4.0,6.0,6.0,10.0,23.0,9.0,15.0,7.0,18.0,0.0,0.0,0.0,4.0,100.0,60.0,0.0,0.0,831687.0,185378.0,65900.0,203159.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,2000,2000,2000.0,36 months,17.97,72.28,D,D1,Account Manager,4 years,RENT,51000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,606xx,IL,2.40,0.0,Nov-2004,1.0,NaN,NaN,1.0,0.0,0,NaN,9.0,w,1914.71,1914.71,141.56,141.56,85.29,56.27,0.0,0.0,0.0,Feb-2019,72.28,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,854.0,0.0,0.0,2.0,3.0,7.0,0.0,NaN,0.0,1.0,0.0,100.0,0.0,0.0,0.0,1.0,4.0,854.0,NaN,NaN,0.0,0.0,169.0,40.0,23.0,7.0,0.0,NaN,NaN,1.0,NaN,0.0,0.0,0.0,0.0,3.0,5.0,0.0,3.0,0.0,1.0,0.0,0.0,0.0,2.0,100.0,NaN,0.0,0.0,854.0,854.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,6000,6000,6000.0,36 months,13.56,203.79,C,C1,Assistant Director,10+ years,RENT,65000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,460xx,IN,30.10,0.0,Nov-1997,0.0,NaN,NaN,19.0,0.0,38476,69.3,37.0,w,5864.01,5864.01,201.53,201.53,135.99,65.54,0.0,0.0,0.0,Feb-2019,208.31,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,91535.0,0.0,5.0,0.0,1.0,23.0,53059.0,87.0,0.0,2.0,9413.0,74.0,55500.0,1.0,2.0,0.0,3.0,5085.0,3034.0,90.8,0.0,0.0,169.0,253.0,13.0,13.0,1.0,14.0,NaN,13.0,NaN,0.0,7.0,12.0,8.0,10.0,15.0,14.0,20.0,12.0,19.0,0.0,0.0,0.0,0.0,100.0,85.7,0.0,0.0,117242.0,91535.0,33100.0,61742.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DirectPay,N,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,5000,5000,5000.0,36 months,17.97,180.69,D,D1,Legal Assistant III,10+ years,MORTGAGE,53580.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,327xx,FL,21.16,0.0,Aug-1998,1.0,32.0,NaN,8.0,0.0,8018,35.2,38.0,w,4786.79,4786.79,353.89,353.89,213.21,140.68,0.0,0.0,0.0,Feb-2019,180.69,Mar-2019,Feb-2019,0.0,45.0,1,Individual,NaN,NaN,NaN,0.0,0.0,41882.0,5.0,2.0,5.0,5.0,3.0,33864.0,98.0,1.0,6.0,3132.0,73.0,22800.0,2.0,1.0,4.0,12.0,5235.0,13786.0,35.9,0.0,0.0,145.0,244.0,6.0,3.0,3.0,6.0,33.0,2.0,32.0,2.0,4.0,5.0,5.0,10.0,20.0,6.0,15.0,5.0,8.0,0.0,0.0,0.0,6.0,78.9,60.0,0.0,0.0,57426.0,41882.0,21500.0,34626.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,6000,6000,6000.0,36 months,14.47,206.44,C,C2,NaN,< 1 year,OWN,300000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,068xx,CT,17.43,1.0,Apr-2002,1.0,17.0,NaN,38.0,0.0,65950,49.8,58.0,w,5730.20,5730.20,405.64,405.64,269.80,135.84,0.0,0.0,0.0,Feb-2019,206.44,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,349502.0,1.0,4.0,1.0,3.0,7.0,39961.0,45.0,1.0,12.0,15926.0,48.0,132500.0,2.0,2.0,2.0,15.0,9197.0,38683.0,60.6,0.0,0.0,166.0,200.0,4.0,4.0,1.0,4.0,NaN,4.0,17.0,0.0,16.0,20.0,19.0,26.0,9.0,33.0,48.0,20.0,38.0,0.0,0.0,0.0,2.0,100.0,26.3,0.0,0.0,477390.0,105911.0,98300.0,89600.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

> ### **Important thing to notice is that there are a lot of missing values or NAN. So, first we can view the columns that have all values missing.**

In [6]:
# This returns the toal number of null values present in each column.
pd.options.display.max_rows = None
loan_dataset.isnull().sum()

id                                            2260668
member_id                                     2260668
loan_amnt                                           0
funded_amnt                                         0
funded_amnt_inv                                     0
term                                                0
int_rate                                            0
installment                                         0
grade                                               0
sub_grade                                           0
emp_title                                      166969
emp_length                                     146907
home_ownership                                      0
annual_inc                                          4
verification_status                                 0
issue_d                                             0
loan_status                                         0
pymnt_plan                                          0
url                                           2260668
desc                                          2134603
purpose                                             0
title                                           23326
zip_code                                            1
addr_state                                          0
dti                                              1711
delinq_2yrs                                        29
earliest_cr_line                                   29
inq_last_6mths                                     30
mths_since_last_delinq                        1158502
mths_since_last_record                        1901512
open_acc                                           29
pub_rec                                            29
revol_bal                                           0
revol_util                                       1802
total_acc                                          29
initial_list_status                                 0
out_prncp                                           0
out_prncp_inv                                       0
total_pymnt                                         0
total_pymnt_inv                                     0
total_rec_prncp                                     0
total_rec_int                                       0
total_rec_late_fee                                  0
recoveries                                          0
collection_recovery_fee                             0
last_pymnt_d                                     2426
last_pymnt_amnt                                     0
next_pymnt_d                                  1303607
last_credit_pull_d                                 73
collections_12_mths_ex_med                        145
mths_since_last_major_derog                   1679893
policy_code                                         0
application_type                                    0
annual_inc_joint                              2139958
dti_joint                                     2139962
verification_status_joint                     2144938
acc_now_delinq                                     29
tot_coll_amt                                    70276
tot_cur_bal                                     70276
open_acc_6m                                    866130
open_act_il                                    866129
open_il_12m                                    866129
open_il_24m                                    866129
mths_since_rcnt_il                             909924
total_bal_il                                   866129
il_util                                       1068850
open_rv_12m                                    866129
open_rv_24m                                    866129
max_bal_bc                                     866129
all_util                                       866348
total_rev_hi_lim                                70276
inq_fi                                         866129
total_cu_tl                                    866130
inq_last_12m                                   866130
acc_open_past_24mths                            50030
avg_cur_bal                                     70346
bc_open_to_buy                                  74935
bc_util                                         76071
chargeoff_within_12_mths                          145
delinq_amnt                                        29
mo_sin_old_il_acct                             139071
mo_sin_old_rev_tl_op                            70277
mo_sin_rcnt_rev_tl_op                           70277
mo_sin_rcnt_tl                                  70276
mort_acc                                        50030
mths_since_recent_bc                            73412
mths_since_recent_bc_dlq                      1740967
mths_since_recent_inq                          295435
mths_since_recent_revol_delinq                1520309
num_accts_ever_120_pd                           70276
num_actv_bc_tl                                  70276
num_actv_rev_tl                                 70276
num_bc_sats                                     58590
num_bc_tl                                       70276
num_il_tl                                       70276
num_op_rev_tl                                   70276
num_rev_accts                                   70277
num_rev_tl_bal_gt_0                             70276
num_sats                                        58590
num_tl_120dpd_2m                               153657
num_tl_30dpd                                    70276
num_tl_90g_dpd_24m                              70276
num_tl_op_past_12m                              70276
pct_tl_nvr_dlq                                  70431
percent_bc_gt_75                                75379
pub_rec_bankruptcies                             1365
tax_liens                                         105
tot_hi_cred_lim                                 70276
total_bal_ex_mort                               50030
total_bc_limit                                  50030
total_il_high_credit_limit                      70276
revol_bal_joint                               2152648
sec_app_earliest_cr_line                      2152647
sec_app_inq_last_6mths                        2152647
sec_app_mort_acc                              2152647
sec_app_open_acc                              2152647
sec_app_revol_util                            2154484
sec_app_open_act_il                           2152647
sec_app_num_rev_accts                         2152647
sec_app_chargeoff_within_12_mths              2152647
sec_app_collections_12_mths_ex_med            2152647
sec_app_mths_since_last_major_derog           2224726
hardship_flag                                       0
hardship_type                                 2250055
hardship_reason                               2250055
hardship_status                               2250055
deferral_term                                 2250055
hardship_amount                               2250055
hardship_start_date                           2250055
hardship_end_date                             2250055
payment_plan_start_date                       2250055
hardship_length                               2250055
hardship_dpd                                  2250055
hardship_loan_status                          2250055
orig_projected_additional_accrued_interest    2252242
hardship_payoff_balance_amount                2250055
hardship_last_payment_amount                  2250055
disbursement_method                                 0
debt_settlement_flag                                0
debt_settlement_flag_date                     2227612
settlement_status                             2227612
settlement_date                               2227612
settlement_amount                             2227612
settlement_percentage                         2227612
settlement_term                               2227612
dtype: int64

In [7]:
# This gives us the name of the columns where all entries are missing.
loan_dataset.columns[loan_dataset.isna().all()].tolist()

['id', 'member_id', 'url']

In [8]:
((loan_dataset['loan_amnt'] == loan_dataset['funded_amnt']).sum(), 
 (loan_dataset['loan_amnt'] == loan_dataset['funded_amnt']).sum() / len(loan_dataset))

(np.int64(2258603), np.float64(0.9990865531780871))

In [9]:
((loan_dataset['funded_amnt_inv'] == loan_dataset['funded_amnt']).sum(),
(loan_dataset['funded_amnt_inv'] == loan_dataset['funded_amnt']).sum() / len(loan_dataset))

(np.int64(2109556), np.float64(0.9331560406039277))

In [10]:
((loan_dataset['loan_amnt'] == loan_dataset['funded_amnt_inv']).sum(), 
(loan_dataset['loan_amnt'] == loan_dataset['funded_amnt_inv']).sum() / len(loan_dataset))

(np.int64(2109166), np.float64(0.932983525223518))

### 💡 Observation on `loan_amnt`, `funded_amnt`, and `funded_amnt_inv`:

- `loan_amnt` represents the **amount requested** by the borrower.
- `funded_amnt` represents the **amount actually funded** by the bank.
- `funded_amnt_inv` represents the **total amount committed by investors** for that loan at that point in time.

> As per the data,
>
> > **99.91% of the time** the `funded_amnt` was equal to the `loan_amnt`.
> >
> > **93.31% of the time** the `funded_amnt` was equal to the `funded_amnt_inv`.
> >
> > **93.29% of the time** the `funded_amnt_inv` was equal to the `loan_amnt`.
> >

👉 This shows that these three variables are highly correlated with each other and including all three variables would be redundant. We can safely **retain only one** (preferably `funded_amnt`) and drop the other two.

In [11]:
# This assigns a unique ID to each record, but it will be similar to serial number of the df. Hence, not keep it.
# loan_dataset['id'] = range(len(loan_dataset)) 

loan_dataset.drop(columns=['id', 'member_id', 'url', 'loan_amnt', 'funded_amnt_inv'], inplace=True) 

# Dropping id, member id, and URL as all were completely empty.
# Dropping 'loan_amnt', as it have extremely high correlation with 'funded_amnt'

In [12]:
loan_dataset.info() # To get additional information about a dataset.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2260668 entries, 0 to 2260667
Columns: 140 entries, funded_amnt to settlement_term
dtypes: float64(101), int64(3), object(36)
memory usage: 2.4+ GB

In [13]:
# To save the current version of our dataset.

loan_dataset.to_csv('dataset/loan1.csv', index=False)